if [ $# -eq 0 ]
then
    output="./home-static.appcache"
else
    output=$1    
fi
    
rm -f $output

echo "CACHE MANIFEST" >> $output
echo "# Generated by genappcache.sh" >> $output
echo "# $(date)" >> $output
echo "" >> $output
echo "CACHE:" >> $output

find . -maxdepth 1 -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./css -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./js -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./lib -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./res -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./spec -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
find ./templates  -name "*.js" -o -name "*.html" -o -name "*.css" >> $output
# vendor: "*.*" since there are fonts files
find ./vendor -name "*.js" -o -name "*.css" -o -name "*.eot" -o -name "*.svg" -o -name "*.ttf" -o -name "*.woff" >> $output
#find ./wysihtml5 -name "*.js" -o -name "*.html" -o -name "*.css" >> $output

find ./img -name "*.*" -not -name ".*" >> $output

echo "" >> $output
echo "NETWORK:" >> $output
echo "*" >> $output

echo "" >> $output
echo "FALLBACK:" >> $output

echo "Done, output to file: $output"
